<?php // NOT NEEDED HERE > if ( ! defined('WOODMART_THEME_DIR')) exit('No direct script access allowed');

/**
 * ------------------------------------------------------------------------------------------------
 * CSS parts variables for CSS Generator
 * ------------------------------------------------------------------------------------------------
 */

return apply_filters(
	'woodmart_css_parts',
	array(
		/**
		 * WooCommerce styles.
		 */
		'wooComm'                       => array(
			'id'      => 'wooComm',
			'title'   => 'WooCommerce',
			'section' => 'WooCommerce styles',
			'checked' => true,
		),
		
		/**
		 * Products grid styles.
		 */
		'wc-shop'                       => array(
			'id'      => 'wc-shop',
			'title'   => 'Products grid styles',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'hov-base'                      => array(
			'id'      => 'hov-base',
			'title'   => 'Hover base',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/products-grid-styles/grid-style-base.jpg',
		),
		'hov-alt'                       => array(
			'id'      => 'hov-alt',
			'title'   => 'Hover alternative',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/products-grid-styles/grid-style-alternative.jpg',
		),
		'hov-button'                    => array(
			'id'      => 'hov-button',
			'title'   => 'Hover button',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/products-grid-styles/grid-style-botton.jpg',
		),
		'hov-full-info'                 => array(
			'id'      => 'hov-full-info',
			'title'   => 'Hover full information',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/products-grid-styles/grid-style-full-information.jpg',
		),
		'hov-info-alt'                  => array(
			'id'      => 'hov-info-alt',
			'title'   => 'Full information alternative',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/products-grid-styles/grid-style-full-information-alternative.jpg',
		),
		'hov-quick'                     => array(
			'id'      => 'hov-quick',
			'title'   => 'Hover quick shop',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/products-grid-styles/grid--style-quik-shop.jpg',
		),
		'hov-standard'                  => array(
			'id'      => 'hov-standard',
			'title'   => 'Standard button',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/products-grid-styles/grid-style-standart-botton.jpg',
		),
		'hov-tiled'                     => array(
			'id'      => 'hov-tiled',
			'title'   => 'Tiled products',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/products-grid-styles/grid-style-tiled-products.jpg',
		),
		'hov-list'                      => array(
			'id'      => 'hov-list',
			'title'   => 'Products list',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/products-grid-styles/grid-style-list.jpg',
		),

		/**
		 * Product categories.
		 */
		'cat-general'                   => array(
			'id'      => 'cat-general',
			'title'   => 'Product categories',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'cat-default'                   => array(
			'id'      => 'cat-default',
			'title'   => 'Default style',
			'section' => 'WooCommerce styles',
			'parent'  => 'cat-general',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-categories/categories-default.jpg',
		),
		'cat-alt'                       => array(
			'id'      => 'cat-alt',
			'title'   => 'Alternative style',
			'section' => 'WooCommerce styles',
			'parent'  => 'cat-general',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-categories/categories-alternative.jpg',
		),
		'cat-center'                    => array(
			'id'      => 'cat-center',
			'title'   => 'Centered style',
			'section' => 'WooCommerce styles',
			'parent'  => 'cat-general',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-categories/categories-centered.jpg',
		),
		'cat-title-rep'                 => array(
			'id'      => 'cat-title-rep',
			'title'   => 'Replace title',
			'section' => 'WooCommerce styles',
			'parent'  => 'cat-general',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-categories/categories-replace-title.jpg',
		),
		
		/**
		 * Modules.
		 */
		'wc-modules'                    => array(
			'id'      => 'wc-modules',
			'title'   => 'Modules',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'quick-view'                    => array(
			'id'      => 'quick-view',
			'title'   => 'Quick view',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/quik-view.jpg',
		),
		'size-guid'                     => array(
			'id'      => 'size-guid',
			'title'   => 'Size guide',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/size-guide.jpg',
		),
		'stock-progress-bar'            => array(
			'id'      => 'stock-progress-bar',
			'title'   => 'Stock progress bar',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/stock-progress-bar.jpg',
		),
		'add-to-cart-popup'             => array(
			'id'      => 'add-to-cart-popup',
			'title'   => 'Popup after add to cart',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/add-to-cart-popup.jpg',
		),
		'rounded-product-labels'        => array(
			'id'      => 'rounded-product-labels',
			'title'   => 'Rounded product labels',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/rounded-product-labels.jpg',
		),
		'rectangular-product-labels'    => array(
			'id'      => 'rectangular-product-labels',
			'title'   => 'Rectangular product labels',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/rectangular-product-labels.jpg',
		),
		'highlight-prod'                => array(
			'id'      => 'highlight-prod',
			'title'   => 'Highlighted product',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/highlighted-product.jpg',
		),
		'bordered-prod'                 => array(
			'id'      => 'bordered-prod',
			'title'   => 'Bordered product',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/bordered.jpg',
		),
		'filter-area'                   => array(
			'id'      => 'filter-area',
			'title'   => 'Filters area',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/filters-area.jpg',
		),
		'compare-prod'                  => array(
			'id'      => 'compare-prod',
			'title'   => 'Compare',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/compare.jpg',
		),
		'wishlist'                      => array(
			'id'      => 'wishlist',
			'title'   => 'Wishlist',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/wishlist.jpg',
		),
		
		/**
		 * Wc plugins.
		 */
		'wc-plugins'                    => array(
			'id'      => 'wc-plugins',
			'title'   => 'Plugins',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'curr-switch'                   => array(
			'id'      => 'curr-switch',
			'title'   => 'Currency switcher',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'germanized'                    => array(
			'id'      => 'germanized',
			'title'   => 'Germanized',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'yith-vend'                     => array(
			'id'      => 'yith-vend',
			'title'   => 'YITH Vendors',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'yith-wishlist'                 => array(
			'id'      => 'yith-wishlist',
			'title'   => 'YITH Wishlist',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => false,
		),
		'yith-compare'                  => array(
			'id'      => 'yith-compare',
			'title'   => 'YITH Compare',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => false,
		),
		'yith-request-quote'            => array(
			'id'      => 'yith-request-quote',
			'title'   => 'YITH Request a quote',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'vc-vend'                       => array(
			'id'      => 'vc-vend',
			'title'   => 'WC Vendors',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'dokon-vend'                    => array(
			'id'      => 'dokon-vend',
			'title'   => 'Dokan',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'marketplace-vend'              => array(
			'id'      => 'marketplace-vend',
			'title'   => 'WC Marketplace',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'wcfm-vend'                     => array(
			'id'      => 'wcfm-vend',
			'title'   => 'WCFM Marketplace',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => false,
		),
		'paypal-express'                => array(
			'id'      => 'paypal-express',
			'title'   => 'PayPal express',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'stripe'                        => array(
			'id'      => 'stripe',
			'title'   => 'Stripe',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		
		/**
		 * Product page styles.
		 */
		'wc-product'                    => array(
			'id'      => 'wc-product',
			'title'   => 'Product page styles',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'product-instagram'             => array(
			'id'      => 'product-instagram',
			'title'   => 'Product instagram',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-instagram.jpg',
		),
		'product-breadcrumbs'           => array(
			'id'      => 'product-breadcrumbs',
			'title'   => 'Product breadcrumbs',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-breadcrumbs.jpg',
		),
		'product-navigation'            => array(
			'id'      => 'product-navigation',
			'title'   => 'Product navigation',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-navigation.jpg',
		),
		'reviews'                       => array(
			'id'      => 'reviews',
			'title'   => 'Reviews',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/reviews.jpg',
		),
		'product-share'                 => array(
			'id'      => 'product-share',
			'title'   => 'Product share',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-share.jpg',
		),
		'meta-location-summary'         => array(
			'id'      => 'meta-location-summary',
			'title'   => 'Meta location after add to cart',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/meta-location-summary.jpg',
		),
		'meta-location-after-tabs'      => array(
			'id'      => 'meta-location-after-tabs',
			'title'   => 'Meta location after tabs',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/meta-location-after-tabs.jpg',
		),
		'product-summary-shadow'        => array(
			'id'      => 'product-summary-shadow',
			'title'   => 'Product summary shadow',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-summary-shadow.jpg',
		),
		'single-product-brand'          => array(
			'id'      => 'single-product-brand',
			'title'   => 'Single product brand',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/single-product-brand.jpg',
		),
		'product-design-default'        => array(
			'id'      => 'product-design-default',
			'title'   => 'Product design default',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-design-default.jpg',
		),
		'product-design-centered'       => array(
			'id'      => 'product-design-centered',
			'title'   => 'Product design centered',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-design-centered.jpg',
		),
		'product-sidebar'               => array(
			'id'      => 'product-sidebar',
			'title'   => 'Product sidebar',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-sidebar.jpg',
		),
		'product-left-thumbnails'       => array(
			'id'      => 'product-left-thumbnails',
			'title'   => 'Product left thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-left-thumbnails.jpg',
		),
		'product-bottom-thumbnails'     => array(
			'id'      => 'product-bottom-thumbnails',
			'title'   => 'Product bottom thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-bottom-thumbnails.jpg',
		),
		'product-column-thumbnails'     => array(
			'id'      => 'product-column-thumbnails',
			'title'   => 'Product column thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-column-thumbnails.gif',
		),
		'product-2-columns-thumbnails'  => array(
			'id'      => 'product-2-columns-thumbnails',
			'title'   => 'Product 2 columns thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-2-columns-thumbnails.gif',
		),
		'product-combined-thumbnails'   => array(
			'id'      => 'product-combined-thumbnails',
			'title'   => 'Product combined thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-combined-thumbnails.gif',
		),
		'product-centered-thumbnails'   => array(
			'id'      => 'product-centered-thumbnails',
			'title'   => 'Product centered thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-centered-thumbnails.jpg',
		),
		'product-full-width-thumbnails' => array(
			'id'      => 'product-full-width-thumbnails',
			'title'   => 'Product full-width thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-full-width-thumbnails.jpg',
		),
		'tabs-layout-tabs'              => array(
			'id'      => 'tabs-layout-tabs',
			'title'   => 'Tabs layout default',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/tabs-layout-tabs.jpg',
		),
		'tabs-layout-accordion'         => array(
			'id'      => 'tabs-layout-accordion',
			'title'   => 'Tabs layout accordion',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/tabs-layout-accordion.jpg',
		),
		'product-thumbnail-buttons'     => array(
			'id'      => 'product-thumbnail-buttons',
			'title'   => 'Product thumbnail buttons',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-thumbnail-buttons.jpg',
		),
		'variable-product'              => array(
			'id'      => 'variable-product',
			'title'   => 'Variable product',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/variable-product.jpg',
		),
		'product-swatches'              => array(
			'id'      => 'product-swatches',
			'title'   => 'Product-swatches',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/product-swatches.jpg',
		),
		'sticky-add-to-cart'            => array(
			'id'      => 'sticky-add-to-cart',
			'title'   => 'Sticky add to cart',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/sticky-addto-cart.jpg',
		),
		'grouped-product'               => array(
			'id'      => 'grouped-product',
			'title'   => 'Grouped product',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/grouped-product.jpg',
		),
		'upsells-widget'                => array(
			'id'      => 'upsells-widget',
			'title'   => 'Upsells widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/product-page-styles/upsells-widget.jpg',
		),
		
		/**
		 * Shop page styles.
		 */
		'wc-shop-page'                  => array(
			'id'      => 'wc-shop-page',
			'title'   => 'Shop page styles',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'shop-title-categories'         => array(
			'id'      => 'shop-title-categories',
			'title'   => 'Shop title categories',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/shop-page-styles/shop-title-categories.jpg',
		),
		'product-loader'                => array(
			'id'      => 'product-loader',
			'title'   => 'Product loader',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/shop-page-styles/product-loader.gif',
		),
		'active-filters'                => array(
			'id'      => 'active-filters',
			'title'   => 'Active filters',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/shop-page-styles/active-filters.jpg',
		),
		'result-count'                  => array(
			'id'      => 'result-count',
			'title'   => 'Result count',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/shop-page-styles/result-count.jpg',
		),
		'products-ordering'             => array(
			'id'      => 'products-ordering',
			'title'   => 'Products ordering',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/shop-page-styles/products-ordering.jpg',
		),
		'products-per-page'             => array(
			'id'      => 'products-per-page',
			'title'   => 'Products per page',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/shop-page-styles/products-per-page.jpg',
		),
		'shop-view'                     => array(
			'id'      => 'shop-view',
			'title'   => 'Shop products view',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/shop-page-styles/shop-view.jpg',
		),
		'woocommerce-pagination'        => array(
			'id'      => 'woocommerce-pagination',
			'title'   => 'Shop pagination',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/shop-page-styles/woocommerce-pagination.jpg',
		),

		/**
		* WooCommerce pages.
		*/
		'wc-page'                       => array(
			'id'      => 'wc-page',
			'title'   => 'Pages',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'cart'                          => array(
			'id'      => 'cart',
			'title'   => 'Cart',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/pages/cart.jpg',
		),
		'checkout'                      => array(
			'id'      => 'checkout',
			'title'   => 'Checkout',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/pages/checkout.jpg',
		),
		'login-register'                => array(
			'id'      => 'login-register',
			'title'   => 'Login & Register',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/pages/login-register.jpg',
		),
		'social-login'                  => array(
			'id'      => 'social-login',
			'title'   => 'Social login',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/pages/social-login.jpg',
		),
		'my-account'                    => array(
			'id'      => 'my-account',
			'title'   => 'My account',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/pages/my-account.jpg',
		),
		'order-page'                    => array(
			'id'      => 'order-page',
			'title'   => 'Order page',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/pages/order-page.jpg',
		),
		
		/**
		 * Widgets.
		 */
		'wc-widgets'                    => array(
			'id'      => 'wc-widgets',
			'title'   => 'Widgets',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'layered-nav-widget'            => array(
			'id'      => 'layered-nav-widget',
			'title'   => 'Layered nav widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/widgets/layered-nav-widget.jpg',
		),
		'product-categories-widget'     => array(
			'id'      => 'product-categories-widget',
			'title'   => 'Product categoires widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/widgets/product-categories-widget.jpg',
		),
		'product-list-widget'           => array(
			'id'      => 'product-list-widget',
			'title'   => 'Product list widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/widgets/product-list-widget.jpg',
		),
		'price-filter-widget'           => array(
			'id'      => 'price-filter-widget',
			'title'   => 'Price filter widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/widgets/price-filter-widget.jpg',
		),
		'slider-price-filter-widget'    => array(
			'id'      => 'slider-price-filter-widget',
			'title'   => 'Slider price filter widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/widgets/slider-price-filter-widget.jpg',
		),
		'rating-filter-widget'          => array(
			'id'      => 'rating-filter-widget',
			'title'   => 'Filter products by rating',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/widgets/rating-filter-widget.jpg',
		),
		'attribute-filter-widget'       => array(
			'id'      => 'attribute-filter-widget',
			'title'   => 'Filter products by attribute',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/widgets/attribute-filter-widget.jpg',
		),
		'active-filters-widget'         => array(
			'id'      => 'active-filters-widget',
			'title'   => 'Active product filters',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/widgets/active-filters-widget.jpg',
		),
		'sort-by-widget'                => array(
			'id'      => 'sort-by-widget',
			'title'   => 'Sort by widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/widgets/sort-by-widget.jpg',
		),
		'cart-widget'                   => array(
			'id'      => 'cart-widget',
			'title'   => 'Cart widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/widgets/cart-widget.jpg',
		),

		/**
		 * Modules.
		 */
		'wc-extra_modules'              => array(
			'id'      => 'wc-extra_modules',
			'title'   => 'Modules',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'woocommerce-notices'           => array(
			'id'      => 'woocommerce-notices',
			'title'   => 'Woocommerce notices',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-extra_modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/woocommerce-notices.jpg',
		),
		'star-rating'                   => array(
			'id'      => 'star-rating',
			'title'   => 'Star rating',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-extra_modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/modules/star-rating.jpg',
		),
		
		/**
		 * Extra configuration.
		 */
		'rtl'                           => array(
			'id'      => 'rtl',
			'title'   => 'RTL language',
			'section' => 'Extra configuration',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/extra/home-rtl.jpg',
		),
		'woodmart-dark'                 => array(
			'id'      => 'woodmart-dark',
			'title'   => 'Dark color scheme',
			'section' => 'Extra configuration',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/extra/demo-dark.jpg',
		),
		
		/**
		 * WPBakery Page Builder.
		 */
		'wpbakery'                      => array(
			'id'      => 'wpbakery',
			'title'   => 'WPBakery Page Builder',
			'section' => 'WPBakery elements',
			'checked' => true,
		),
		'el-brand'                      => array(
			'id'      => 'el-brand',
			'title'   => 'Brands',
			'section' => 'WooCommerce styles',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/brands-element.jpg',
		),
		'el-product-tabs'               => array(
			'id'      => 'el-product-tabs',
			'title'   => 'Product tabs',
			'section' => 'WooCommerce styles',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/products tabs.jpg',
		),
		'banner'                        => array(
			'id'      => 'banner',
			'title'   => 'Promo banner',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/banners.jpg',
		),
		'timer'                         => array(
			'id'      => 'timer',
			'title'   => 'Countdown timer',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/countdown-timer.jpg',
		),
		'counter'                       => array(
			'id'      => 'counter',
			'title'   => 'Counter',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/animated-counter.jpg',
		),
		'map'                           => array(
			'id'      => 'map',
			'title'   => 'Google map',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/google-maps.jpg',
		),
		'gallery'                       => array(
			'id'      => 'gallery',
			'title'   => 'Images gallery',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/images-gallery.jpg',
		),
		'hotspot'                       => array(
			'id'      => 'hotspot',
			'title'   => 'Images hotspot',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/image-hotspot.jpg',
		),
		'info-box'                      => array(
			'id'      => 'info-box',
			'title'   => 'Information box',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/infobox.jpg',
		),
		'instagram'                     => array(
			'id'      => 'instagram',
			'title'   => 'Instagram',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/instagram.jpg',
		),
		'list'                          => array(
			'id'      => 'list',
			'title'   => 'Icon list',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/list-element.jpg',
		),
		'menu-price'                    => array(
			'id'      => 'menu-price',
			'title'   => 'Menu price',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/menu-price.jpg',
		),
		'pricing-table'                 => array(
			'id'      => 'pricing-table',
			'title'   => 'Pricing table',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/pricing-tables.jpg',
		),
		'row-divider'                   => array(
			'id'      => 'row-divider',
			'title'   => 'Row divider',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/section-dividers.jpg',
		),
		'sec-title'                     => array(
			'id'      => 'sec-title',
			'title'   => 'Section title',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/titles.jpg',
		),
		'responsive-text'               => array(
			'id'      => 'responsive-text',
			'title'   => 'Responsive text block',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/responsive-text-block.jpg',
		),
		'slider'                        => array(
			'id'      => 'slider',
			'title'   => 'WoodMart slider',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/sliders.jpg',
		),
		'team-member'                   => array(
			'id'      => 'team-member',
			'title'   => 'Team member',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/team-member.jpg',
		),
		'author-area'                   => array(
			'id'      => 'author-area',
			'title'   => 'Author area',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/author-area.jpg',
		),
		'testimonial'                   => array(
			'id'      => 'testimonial',
			'title'   => 'Testimonials',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/testimonials.jpg',
		),
		'timeline'                      => array(
			'id'      => 'timeline',
			'title'   => 'Timeline',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/timeline.jpg',
		),
		'twitter'                       => array(
			'id'      => 'twitter',
			'title'   => 'Twitter',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/twiter-wb.jpg',
		),
		'deg360'                        => array(
			'id'      => 'deg360',
			'title'   => '360 degree view',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/360-degree-view.jpg',
		),
		'vc-accordion'                  => array(
			'id'      => 'vc-accordion',
			'title'   => 'VC Accordion',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/vc-acordion.jpg',
		),
		'vc-tabs'                       => array(
			'id'      => 'vc-tabs',
			'title'   => 'VC Tabs',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/vc-tabs.jpg',
		),
		'track-order'                   => array(
			'id'      => 'track-order',
			'title'   => 'Order tracking form',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/woocommerce/wpbakery-page-builder/track-order.jpg',
		),
		
		/**
		 * Additional plugins.
		 */
		'extra-plugins'                 => array(
			'id'      => 'extra-plugins',
			'title'   => 'Plugins',
			'section' => 'Additional plugins',
			'checked' => true,
		),
		'bbpress'                       => array(
			'id'      => 'bbpress',
			'title'   => 'BBPress',
			'section' => 'Additional plugins',
			'parent'  => 'extra-plugins',
			'checked' => false,
		),
		'wpcf7'                         => array(
			'id'      => 'wpcf7',
			'title'   => 'Contact form 7',
			'section' => 'Additional plugins',
			'parent'  => 'extra-plugins',
			'checked' => true,
		),
		'mc4wp'                         => array(
			'id'      => 'mc4wp',
			'title'   => 'Mailchimp',
			'section' => 'Additional plugins',
			'parent'  => 'extra-plugins',
			'checked' => true,
		),
		'wpml'                          => array(
			'id'      => 'wpml',
			'title'   => 'WPML',
			'section' => 'Additional plugins',
			'parent'  => 'extra-plugins',
			'checked' => true,
		),
		
		/**
		 * Portfolio.
		 */
		'portfolio'                     => array(
			'id'      => 'portfolio',
			'title'   => 'Portfolio styles',
			'section' => 'Portfolio',
			'checked' => true,
		),
		'project-hover'                 => array(
			'id'      => 'project-hover',
			'title'   => 'Portfolio base hover',
			'section' => 'Portfolio',
			'parent'  => 'portfolio',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/portfolio/portfolio-base-hover.jpg',
		),
		'project-Alt'                   => array(
			'id'      => 'project-Alt',
			'title'   => 'Alternate hover',
			'section' => 'Portfolio',
			'parent'  => 'portfolio',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/portfolio/alternative-hover.jpg',
		),
		'project-under'                 => array(
			'id'      => 'project-under',
			'title'   => 'Title under image',
			'section' => 'Portfolio',
			'parent'  => 'portfolio',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/portfolio/title-under-image.jpg',
		),
		'project-parallax'              => array(
			'id'      => 'project-parallax',
			'title'   => 'Parallax on mouse move',
			'section' => 'Portfolio',
			'parent'  => 'portfolio',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/portfolio/parallax-mouse-move.jpg',
		),
		
		/**
		 * Blog.
		 */
		'blog-styles'                   => array(
			'id'      => 'blog-styles',
			'title'   => 'Blog style',
			'section' => 'Blog',
			'checked' => true,
		),
		'blog-default'                  => array(
			'id'      => 'blog-default',
			'title'   => 'Default',
			'section' => 'Blog',
			'parent'  => 'blog-styles',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/blog/default.jpg',
		),
		'blog-alt'                      => array(
			'id'      => 'blog-alt',
			'title'   => 'Alternative',
			'section' => 'Blog',
			'parent'  => 'blog-styles',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/blog/alternative.jpg',
		),
		'blog-small-img'                => array(
			'id'      => 'blog-small-img',
			'title'   => 'Small images',
			'section' => 'Blog',
			'parent'  => 'blog-styles',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/blog/small-images.jpg',
		),
		'blog-chess'                    => array(
			'id'      => 'blog-chess',
			'title'   => 'Chess grid',
			'section' => 'Blog',
			'parent'  => 'blog-styles',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/blog/chess-grid.jpg',
		),
		'blog-mask'                     => array(
			'id'      => 'blog-mask',
			'title'   => 'Image mask',
			'section' => 'Blog',
			'parent'  => 'blog-styles',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/blog/image-mask.jpg',
		),
		
		/**
		 * Extra features.
		 */
		'extra-features'                => array(
			'id'      => 'extra-features',
			'title'   => 'Features',
			'section' => 'Extra features',
			'checked' => true,
		),
		'off-canvas-sidebar'            => array(
			'id'      => 'off-canvas-sidebar',
			'title'   => 'Off-canvas sidebar',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/off-canvas-sidebar.jpg',
		),
		'header-banner'                 => array(
			'id'      => 'header-banner',
			'title'   => 'Header banner',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/header-banner.jpg',
		),
		'bottom-toolbar'                => array(
			'id'      => 'bottom-toolbar',
			'title'   => 'Bottom toolbar',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/bottom-toolbar.jpg',
		),
		'cookies'                       => array(
			'id'      => 'cookies',
			'title'   => 'Cookies notice',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/cookies-notice.jpg',
		),
		'wd-search'                        => array(
			'id'      => 'wd-search',
			'title'   => 'Search form',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/search-form.jpg',
		),
		'animations'                    => array(
			'id'      => 'animations',
			'title'   => 'Elements appearance animations',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/appearance-animations.gif',
		),
		'full-menu'                     => array(
			'id'      => 'full-menu',
			'title'   => 'Header full screen menu',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/header-full-screen-menu.jpg',
		),
		'ol-ul-list'                    => array(
			'id'      => 'ol-ul-list',
			'title'   => 'Standard ul and ol styles',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/standard-ul-ol-styles.jpg',
		),
		'form-rounded'                  => array(
			'id'      => 'form-rounded',
			'title'   => 'Rounded forms style',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/form-rounded.jpg',
		),
		'form-circle'                   => array(
			'id'      => 'form-circle',
			'title'   => 'Circled forms style',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/form-circle.jpg',
		),
		'form-underline'                => array(
			'id'      => 'form-underline',
			'title'   => 'Underlined forms style',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/form-underline.jpg',
		),
		'header-dropdown-dark'          => array(
			'id'      => 'header-dropdown-dark',
			'title'   => 'Header dropdowns dark style',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips/features/header-dropdown-dark.jpg',
		),
	)
);
